# Generated by Django 5.2.4 on 2026-01-07 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('mood', models.CharField(choices=[('Relax', 'Relax'), ('Adventure', 'Adventure'), ('Romantic', 'Romantic'), ('Cultural', 'Cultural')], max_length=20)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('reachable_within_days', models.IntegerField(help_text='User can reach destination within these days')),
                ('is_offbeat', models.BooleanField(default=True)),
                ('budget', models.CharField(max_length=50)),
                ('best_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('avg_cost', models.IntegerField()),
                ('image', models.URLField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_places', to='travel.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.IntegerField()),
                ('hotel_type', models.CharField(choices=[('Budget', 'Budget'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury'), ('Homestay', 'Homestay')], max_length=50)),
                ('image', models.URLField()),
                ('rating', models.FloatField(default=4.0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travel.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('Train', 'Train'), ('Bus', 'Bus'), ('Flight', 'Flight')], max_length=20)),
                ('from_city', models.CharField(default='Kolkata', max_length=100)),
                ('travel_time_hours', models.FloatField(default=0)),
                ('approx_cost', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='travel.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
