# Generated by Django 5.2.4 on 2026-01-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='food_place',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_route',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.IntegerField(),
        ),
    ]
