# Generated by Django 5.2.4 on 2026-01-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_booking_food_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
