# Generated by Django 6.0 on 2026-01-11 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_booking_id_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_mode',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
